## command to create environment variable and make it persistent 
echo 'export PROJECT=MERCURY' >> ~/.profile

## Command to create alias for the command and make it persistent
echo 'alias up=uptime' >> ~/.profile

## command to check current user shell
cat /etc/passwd

## command to change shell type of current user to bourne shell
sudo usermod bob -s /bin/sh

## command to change prompt so that it displays the date as per the format below:
# Example: [Wed Apr 22]bob@caleston-lp10:~$
echo 'PS1=[\d]\u@\h:\w$' >> ~/.profile

## command to know the current linux version
uname -r

## command to print messages generated by kernel
dmesg

## how many block device of type disk is available on system
lsblk|grep disk

## command to ge the default systemd target set in the system
systemctl get-default

## command to set the default systemd target in the system
systemctl set-default

## what directory contain block devices on the system
/dev

## command to check the vendor for the ethernet controller used in this system
lspci | grep -E -i --color 'network|ethernet'

## Command to check iptables
iptables -L

## Command to append new iptables rules to add incoming rule permitting ssh connection from source IP
sudo iptables -A INPUT -p tcp -s 172.16.238.187 --dport 22 -j ACCEPT

## command to get default systemd target
systemctl get-default

## Command to set the default target of systemd
systemctl set-default multi-user.target

## Which directory contains the files related to the block devices that can be seen when running the lsblk command
/dev

## command to get the name of the vendor for the Ethernet Controller used in the system
lspci

## default package manager on debian system 
dpkg

## install package on debian system
sudo dpkg -i <PACKAGE_NAME>

## command to remove package in ubuntu
sudo apt remove <package_name>

## command to find file using name
find -name <file_name>

## command to find file in particular directory
find /etc -name <file_name>

## get absolute path of all files having specific string in the file ubuntu
find /etc| xargs grep '<string_name>' -sl

## command to print output of command in a file using echo command
echo "$(find /etc |xargs grep '172.16.238.197' -sl)" > /home/bob/ip

## command to redirect standard error of a commad to a file
python3 /home/bob/my_python_test.py &> /home/bob/py_error.txt

## Read the file /usr/share/man/man1/tail.1.gz and without extracting redirect the contents to a file called /home/bob/pipes.
zcat /usr/share/man/man1/tail.1.gz | tee /home/bob/pipes

## commad to search package using rpm command
rpm -q --whatprovides wget

## command to install packages using rpm package manager
rpm --install --allfiles /home/bob/firefox-x-x-x.rpm

## command to install package via yum packages
yum install firefox

## command ro list all source repositories
yum repolist all

## command to check which package provides the tcpdump command in the centos-lab
yum provides tcpdump

## command to list all cronjobs for the user
crontab -l

## command to edit crontab jobs
crontab -e

## Format of cronjob scheduling
* * * * * ( Minutes, Hours, Day of the Month, Month Number, Day Number(SUN-SAT[0-6]))

## command to know num of disk of block types
lsblk

## command to check size of disk
sudo fdisk -l /dev/vdc

## command to know major no of devices beginnt with vd

ls -lr /dev/*vd

## command to create a GPT partition call vdb1 of size 500M on the disk /dev/vdb
Step1: Install gdisk
sudo apt install gdisk

Step2: Do the partition
sudo gdisk /dev/ddb

## Path of systemd service file 
/etc/systemd/system/sample.service


## Systemctl commands

sudo systemctl status sample.service
sudo systemctl start sample.service
sudo systemctl stop sample.service
sudo systemctl enabled sample.service
sudo systemctl daemon-reload
journalctl -u sample.service

## ip link commands

## command to add feault gateway
sudo ip r default via 172.16.238.1

## command to check if interface is up or not
ip link 

## set interfacte UP
ip link set dev eth0 UP

## command to check ip address
ip a

## command to check defaut connectivity
telnet <name> <port>

## command to delete default route
sudo ip r del default

## command to get which of group chris part of
id chris

## command to check disk type
lsblk

## command to check if file system is created 
sudo df -h

## command to make partition
sudo gdisk /dev/vdb

## command to make partition
sudo mkfs.ext4 /dev/vdb

## create directory /mnt/data
sudo mkdir /mnt/data

## mount the directory to /mnt/data
sudo mount /dev/vdb /mnt/data

## make mount volume persistent across the reboot
make following entry in /etc/fstab file
/dev/vdb        /mnt/data  ext4    rw  0       0


## command to get individual disk size
sudo lsblk

## command to display physical volume
pvdisplay

## command to create physical volume
pvcreate /dev/vdb

## command to create volume group
sudo vgcreate caleston_vg /dev/vdb /dev/vdc

## command to create logical volume
sudo lvcreate -L 1G -n data caleston_vg

## command to create ext4 filesystem on the logical volume and mount it at /mnt/media
mkdir /mnt/media
mkfs.ext4 /dev/mapper/caleston_vg-data
sudo mount /dev/mapper/caleston_vg-data /mnt/media

## add 500M to existing logical volume
sudo lvresize -L +500M -n /dev/mapper/caleston_vg-data
sudo resize2fs /dev/mapper/caleston_vg-data
